#!/bin/sh

if [ "$1" = "" ]  || [ "$2" = "" ]
then
    echo "Provide arguments!"
    echo "arg1: dirname"
    echo "arg2: wildcat to select file"
    exit
else
    echo "converting files in directory $1"
fi


#for i in `seq $1 $2`;
#do
#    echo "*************************************************************************"
#    if [ "$3" = "lasp" ] 
#    then
#	elas_sum lhyd $i > mdata/histdb_dir/${i}_112k.log
#	elas_sum lhyd $i >> mdata/histdb_dir/${i}_112k.log
#	elas_sum alum $i >> mdata/histdb_dir/${i}_112k.log
#	elas_sum prot $i >> mdata/histdb_dir/${i}_112k.log
#done    


for file in $1/$2
do
#    echo "#/.####################################"
    echo "converting $file"
    t9301_db $file
#    echo "#####################################"

done

